# Generated by Django 3.0 on 2021-11-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0002_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='sentimento',
            field=models.IntegerField(choices=[[0, 'a'], [1, 'b'], [2, 'c'], [3, 'd']], default=0),
        ),
    ]
