# Generated by Django 3.0 on 2021-12-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0002_auto_20211130_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Como_estuvo_tu_dia',
            field=models.IntegerField(choices=[[0, 'Bueno'], [1, 'Decente'], [2, 'Normal'], [3, 'Malo'], [4, 'Terrible']], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
