# Generated by Django 3.0 on 2021-11-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0004_formulario_intensidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='detonante',
            field=models.CharField(default='', max_length=200),
        ),
    ]
