# Generated by Django 3.0 on 2021-12-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0004_auto_20211201_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='algo',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
