# Generated by Django 3.0 on 2021-12-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0005_auto_20211201_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
