# Generated by Django 3.0 on 2021-12-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0006_profile_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='porcentaje_buenos',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='porcentaje_decentes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='porcentaje_malos',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='porcentaje_normales',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='porcentaje_terribles',
            field=models.FloatField(default=0),
        ),
    ]
