# Generated by Django 3.0 on 2021-12-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0007_auto_20211201_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howdoyoufeel',
            name='algo',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
