# Generated by Django 3.0 on 2021-12-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0009_auto_20211201_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cuatro_mes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dos_mes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='quinto_mes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='septimo_mes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sexto_mes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tres_mes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='un_mes',
        ),
    ]
