# Generated by Django 3.0 on 2021-12-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0010_auto_20211201_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='escribe_una_palabra',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
