# Generated by Django 3.0 on 2021-12-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0011_profile_escribe_una_palabra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='algo',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='escribe_una_palabra',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
