# Generated by Django 3.0 on 2021-12-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0013_auto_20211201_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='Como_estuvo_tu_dia',
            field=models.IntegerField(blank=True, choices=[[0, 'Bueno'], [1, 'Decente'], [2, 'Normal'], [3, 'Malo'], [4, 'Terrible']], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='algo',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='escribe_una_palabra',
            field=models.CharField(blank=True, default='Write a word', max_length=1000, null=True),
        ),
    ]
