# Generated by Django 3.0 on 2021-12-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0015_auto_20211204_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='content',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
