# Generated by Django 3.0 on 2021-12-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0017_remove_nota_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='content',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
