# Generated by Django 3.0 on 2021-12-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0019_auto_20211204_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='content',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
