# Generated by Django 3.0 on 2021-12-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0020_auto_20211204_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='content',
            field=models.TextField(),
        ),
    ]
