# Generated by Django 3.0 on 2021-12-05 04:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0022_auto_20211205_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
