# Generated by Django 3.0 on 2021-12-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0023_auto_20211205_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contactos',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_boton',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dog',
            name='fecha',
            field=models.CharField(default='2021-12-06', max_length=200),
        ),
    ]
