# Generated by Django 3.0 on 2021-12-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0027_auto_20211207_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_presion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nota',
            name='timestamp',
            field=models.DateTimeField(default='2021-12-07 00:56'),
        ),
    ]
