# Generated by Django 3.0 on 2021-12-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0028_auto_20211207_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_boton',
        ),
        migrations.AlterField(
            model_name='nota',
            name='timestamp',
            field=models.DateTimeField(default='2021-12-07 00:57'),
        ),
    ]
