# Generated by Django 3.0 on 2021-12-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0029_auto_20211207_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contador_angustia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='contador_ansia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='contador_frustracion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='contador_miedo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='contador_rabia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='contador_tristeza',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='contador_verguenza',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='porcentaje_angustia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='porcentaje_ansia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='porcentaje_frustracion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='porcentaje_miedo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='porcentaje_rabia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='porcentaje_tristeza',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='porcentaje_verguenza',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nota',
            name='timestamp',
            field=models.DateTimeField(default='2021-12-07 01:11'),
        ),
    ]
