# Generated by Django 3.0 on 2021-12-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0030_auto_20211207_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='timestamp',
            field=models.DateTimeField(default='2021-12-07 01:53'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='porcentaje_angustia',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='porcentaje_ansia',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='porcentaje_frustracion',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='porcentaje_miedo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='porcentaje_rabia',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='porcentaje_tristeza',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='porcentaje_verguenza',
            field=models.FloatField(default=0),
        ),
    ]
