# Generated by Django 3.0 on 2021-12-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0032_auto_20211207_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howdoyoufeel',
            name='Como_estuvo_tu_dia',
            field=models.IntegerField(choices=[[0, 'Good'], [1, 'Decent'], [2, 'Normal'], [3, 'Bad'], [4, 'Terrible']]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='timestamp',
            field=models.DateTimeField(default='2021-12-07 11:34'),
        ),
    ]
