# Generated by Django 3.0 on 2021-12-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0035_auto_20211207_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sentimiento',
            new_name='sentiment',
        ),
        migrations.AlterField(
            model_name='nota',
            name='timestamp',
            field=models.DateTimeField(default='2021-12-07 17:44'),
        ),
    ]
