# Generated by Django 3.0 on 2021-12-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0037_auto_20211207_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Como_estuvo_tu_dia',
            new_name='How_was_your_day',
        ),
        migrations.AlterField(
            model_name='nota',
            name='timestamp',
            field=models.DateTimeField(default='2021-12-07 18:13'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sentiment',
            field=models.IntegerField(choices=[[0, 'Sadness'], [1, 'Rage'], [2, 'Anguish'], [3, 'Anxiety'], [4, 'Fear'], [5, 'Frustration'], [6, 'Shame']], default=2),
        ),
    ]
