# Generated by Django 3.0 on 2021-12-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0038_auto_20211207_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='escribe_una_palabra',
            new_name='Write_a_word',
        ),
        migrations.AlterField(
            model_name='nota',
            name='timestamp',
            field=models.DateTimeField(default='2021-12-07 18:15'),
        ),
    ]
