# Generated by Django 3.0 on 2021-12-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0039_auto_20211207_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='nombre',
            new_name='Name',
        ),
        migrations.AlterField(
            model_name='nota',
            name='timestamp',
            field=models.DateTimeField(default='2021-12-07 18:16'),
        ),
    ]
