# Generated by Django 3.0 on 2021-12-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0040_auto_20211207_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='timestamp',
            field=models.DateTimeField(default='2021-12-07 23:47'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='How_was_your_day',
            field=models.IntegerField(blank=True, choices=[[0, 'Good'], [1, 'Decent'], [2, 'Normal'], [3, 'Bad'], [4, 'Terrible']], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sentiment',
            field=models.IntegerField(choices=[[0, 'Sadness'], [1, 'Rage'], [2, 'Anguish'], [3, 'Anxiety'], [4, 'Fear'], [5, 'Frustration'], [6, 'Shame']], default=None),
        ),
    ]
