# Generated by Django 3.0 on 2021-12-11 21:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0041_auto_20211207_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='content_movil',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='fecha',
            field=models.CharField(default='2021-12-11', max_length=200),
        ),
        migrations.AlterField(
            model_name='nota',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='timestamp',
            field=models.DateTimeField(default='2021-12-11 18:35'),
        ),
    ]
