# Generated by Django 3.0 on 2021-12-11 21:54

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_relax', '0042_auto_20211211_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='content',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='nota',
            name='content_movil',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='nota',
            name='timestamp',
            field=models.DateTimeField(default='2021-12-11 18:54'),
        ),
    ]
